export default {
  namespace: 'community',

  state: {
    topbar: [{
      id: 1,
      image: 'https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=2182278005,4292695282&fm=27&gp=0.jpg',
      title: '鉴客杂谈',
      caption: '11239讨论',
    },
    {
      id: 2,
      image: 'https://koreawallpaper.com/gallery/91b42e543db273a7837b91605f5b87bc.jpg',
      title: '影视同期声',
      caption: '592讨论',
    },
    {
      id: 3,
      image: 'https://wallpaperstudio10.com/static/wpdb/wallpapers/560x315/167553.jpg',
      title: '古代美女',
      caption: '590讨论',
    },
    {
      id: 4,
      image: 'https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fblogs-images.forbes.com%2Fanthonykarcz%2Ffiles%2F2018%2F04%2Fiphone8-red-wallpaper-featured-1200x675.jpg',
      title: '风云轶事',
      caption: '934讨论',
    },
    {
      id: 5,
      image: 'https://images.pexels.com/photos/640781/pexels-photo-640781.jpeg?auto=compress&cs=tinysrgb&h=350',
      title: '聊书',
      caption: '1051讨论',
    },
    {
      id: 6,
      image: 'https://wallpaperbrowse.com/media/images/minimalism_sky_clouds_sun_mountains_lake_landscape_95458_602x339.jpg',
      title: '文学诗社',
      caption: '380讨论',
    },
    {
      id: 7,
      image: 'https://static.dezeen.com/uploads/2018/04/beyond-the-deep-calico-wallpaper-and-lindsey-adelman-design-products_dezeen_2364_col_3-852x431.jpg',
      title: '秦朝',
      caption: '1226讨论',
    },
    {
      id: 8,
      image: 'https://images.unsplash.com/photo-1517784120905-d9f8d5aced1a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=c6d95ce1f98feb68e16645fe5e603ae4&w=1000&q=80',
      title: '汉朝',
      caption: '983讨论',
    },
    {
      id: 9,
      image: 'https://www.imore.com/sites/imore.com/files/styles/xlarge/public/field/image/2017/11/airplane-view-iphone-x-wallpaper-01.jpg?itok=XjreEpz0',
      title: '三国',
      caption: '2074讨论',
    }],

    wonderful: [{
      id: 1,
      avatar: 'https://www.sammobile.com/wp-content/uploads/2017/03/Samsung-Z1_Wallpaper_03.png',
      name: '山竹独看寒江雪',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '读万卷书，行万里路。',
      title: '中国历史上对周边少数民族...',
      content: '古时候，中国人以居住于天地之中而自诩，把居住于周边的少数民族分为四大类：居住在东边的称为东夷，居住在南...',
      image: 'https://iphonewalls.net/wp-content/uploads/2017/12/Earth%20Satellites%20Sun%20Moon%20Illustration%20iPhone%205%20Wallpaper-320x480.jpg',
      comment: '83',
      like: '34',
      date: '2017-12-13',
    },
    {
      id: 2,
      avatar: 'https://images.anthropologie.com/is/image/Anthropologie/46811956_066_b?$an-category$&qlt=80&fit=constrain',
      name: '宁白瑞普',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '天下风云出吾辈，一入江湖岁月催。峥嵘...',
      title: '83年前的营口坠龙事件之谜',
      content: '（转自微信公众号“志强mook”，版权归原作者盛文强所有）',
      image: 'https://www.wallsandmurals.com/content/images/thumbs/0019111_wg20235_750.jpeg',
      comment: '26',
      like: '48',
      date: '2017-12-12',
    },
    {
      id: 3,
      avatar: 'https://theultralinx.com/.image/ar_8:10%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MTU0MTczMjMyMTQ3MDgwNTI4/schalk-neethling-592618-unsplash.jpg',
      name: '刘琦爱历史',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '自媒体',
      title: '在电视剧里被诸葛亮骂死的...',
      content: '在《三国演义》中，为了彰显诸葛亮的魅力，曹魏司徒王朗只能作为一个反面素材被诸葛亮活活骂死，王朗也因此...',
      image: 'https://www.svenskttenn.se/filtered/2127/rszww800h800-83/svenskt_tenn_tapet_eldblomman_rod--260638475-rszww800h800-83.jpg',
      comment: '35',
      like: '22',
      date: '2017-12-04',
    },
    {
      id: 4,
      avatar: 'https://images.anthropologie.com/is/image/Anthropologie/46811956_066_b?$an-category$&qlt=80&fit=constrain',
      name: '宁白瑞普',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '天下风云出吾辈，一入江湖岁月催。峥嵘...',
      title: '中国古代飞行器简介',
      content: '（版权归原作者盛文强所有，转自微信公众号“志强mook”）',
      image: 'https://images.pexels.com/photos/443446/pexels-photo-443446.jpeg?auto=compress&cs=tinysrgb&h=350',
      comment: '13',
      like: '7',
      date: '2017-12-04',
    },
    {
      id: 5,
      avatar: 'https://wallpaperstudio10.com/static/wpdb/wallpapers/560x315/161455.jpg',
      name: '淡淡地、伤',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '吃瓜群众',
      title: '揭秘明朝最传奇的大富商沈万三...',
      content: '沈万三是元朝末期明朝初期的一个传奇人物，这传奇还要从他的名字说起。原名沈富，字仲荣，被人称为万三...',
      image: 'https://images.unsplash.com/photo-1503509179394-0174d54f46e5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=86ef712f146a6a58770d9ff056686526&w=1000&q=80',
      comment: '28',
      like: '15',
      date: '2017-11-30',
    },
    {
      id: 6,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6QiZwELVhDrwE0z5iPsCxX0PQ2v87mv2CFuGPYJ_404ejBc-L',
      name: '刘琦',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '这个人很懒...我留下了我',
      title: '国粹——认识京剧脸谱',
      content: '“蓝脸的窦尔敦盗御马，红脸的关公战长沙。黄脸的典韦，白脸的曹操，黑脸的张飞叫喳喳...”认识京剧脸谱...',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAlCIYRLQu6jyEy4GoKAoQR3xnCyH4EvIegkqcHGQW6ayvt9zz',
      comment: '21',
      like: '15',
      date: '2017-11-29',
    },
    {
      id: 7,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf6IEtXG3h5SUf-Vif6iS0YEDgc6HJryFaBq3aJvxzu1tXUvykxA',
      name: 'GO!GO去旅游！',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '旅行达人',
      title: '文物',
      content: '黄地珐琅彩梅花纹碗，清雍正',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvbhTxg697MQJUBX9fA63P9rRvkdE65Tv-DIQlxDWdrwKE23XVxA',
      comment: '28',
      like: '6',
      date: '2017-11-28',
    }],

    concern: [{
      id: 1,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsKQ1uHOqRmIjO1X4IqUS-O6PMiBYI-Io9M-yutW17Dh13accv',
      name: '看鉴君',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '看鉴君，在江湖',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_PVh0ub21lOY4IzJfWfln5svxp_Q_h9-m_FWeReV2MfdFFmrMfQ',
      content: '下载看鉴APP',
    },
    {
      id: 2,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6D7FLnoXZxnUToWaBOXCzLnOZ2_6FBw021b1j-iEJpECLXlxxBA',
      name: '看鉴妞',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '妞儿，我是看鉴妞...',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbu6gIsokN3ySQsDzY7OavhzwoBU3bmNtI11fiYaGO4EImFPcQ',
      content: '小米',
    },
    {
      id: 3,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsKQ1uHOqRmIjO1X4IqUS-O6PMiBYI-Io9M-yutW17Dh13accv',
      name: '看鉴君',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '看鉴君，在江湖',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKdzQcM3vEkigEAgAgNBkte-0EgBdd8uvryYI3lyC1qh1p0fLn',
      content: '本期小米活动实物奖品中奖名单',
    },
    {
      id: 4,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6D7FLnoXZxnUToWaBOXCzLnOZ2_6FBw021b1j-iEJpECLXlxxBA',
      name: '看鉴妞',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '妞儿，我是看鉴妞...',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwKuJ5aHmTgAV0bvO5sj-sbfOAoireLaQau6fCJ4XfRdeSsKn5Vw',
      content: '毛主席曾称他为“封建帝王”...',
    },
    {
      id: 5,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsKQ1uHOqRmIjO1X4IqUS-O6PMiBYI-Io9M-yutW17Dh13accv',
      name: '看鉴君',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '看鉴君，在江湖',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2M_IQuBURKP3MiNKkRnYSJJuHlAsJHRrjJpwV6LVN0fjVpU2x',
      content: '鲜卑皇族可能不是胡族',
    },
    {
      id: 6,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6D7FLnoXZxnUToWaBOXCzLnOZ2_6FBw021b1j-iEJpECLXlxxBA',
      name: '看鉴妞',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '妞儿，我是看鉴妞...',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKfKPxHZgNVZYlCMjSYOlxvyo2RjL0xSXPouYf9JiUBsa6bVAUiw',
      content: '《水浒传》中任劳任怨的梁...',
    },
    {
      id: 7,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsKQ1uHOqRmIjO1X4IqUS-O6PMiBYI-Io9M-yutW17Dh13accv',
      name: '看鉴君',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '看鉴君，在江湖',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUoNzJ1Rg5RpAlV162AjjM0-xTX9ZnmZr9MoURlw6fsJ7o2KC4',
      content: '一连串的误判导致的朝鲜战争...',
    }],

    dynamic: [{
      id: 1,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBJ8jngMqySq6vibzJkEBNW3_HsfSonakelXDB3PLZwSEnN4eTpQ',
      name: '刘琦',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '历史爱好者',
      title: '绝无仅有的胖皇帝，把龙椅都坐塌了',
      content: '相传魏征曾问过唐太宗：您知道为什么您是皇帝吗？唐太宗说了很多，结果魏征都不认同，唐太宗就问魏征：那你说是为什么？魏征说因为您坐在这把龙椅上...',
      comment: '0',
      like: '0',
      date: '昨天',
    },
    {
      id: 2,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGZc_QHpPNs64qbG6m9SWtTB0WvWnyUJ_jLoC_wkpP1QymcvT3',
      name: '王华建',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '吃瓜群众',
      title: '李陵为何终究没有回到汉朝？',
      content: '中国古代历史中的忠臣千百年来受人敬仰，奸逆者则遭万世唾弃。然而事无绝对，就有这样一个人随已变节，但却被人深切的同情着，这个人便是李陵...',
      comment: '0',
      like: '0',
      date: '昨天',
    },
    {
      id: 3,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJyx6A-trbicNBvO7pPdasai0rOhCgg0yq5WSePj5o0nNMUsssqA',
      name: '程基锋',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '吃瓜群众',
      title: '明朝最著名的政治家，只因做出了这个...',
      content: '明朝与元朝残余势力蒙古的边境恩怨一直纠缠到明朝末年，清军入关。即便是明朝最著名的政治家张居正，也未能真正解决蒙古产生的辽东边患，最终...',
      comment: '0',
      like: '0',
      date: '昨天',
    },
    {
      id: 4,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5UzrNYvUrBb9Z9IxIB_LqVX-hmjKmW06iSooQRu5-5145m9cbqg',
      name: '时瑞涛',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '吃瓜群众',
      title: '为何唐朝分为初唐、盛唐、中唐、晚唐...',
      content: '有一种说法是，这是指唐朝诗歌的不同分期。其他朝代的文学没有这样明确的分期，因此也就没有“初盛中晚”的说法...',
      comment: '0',
      like: '0',
      date: '昨天',
    },
    {
      id: 5,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnYe_2ZVJqj5SfTVDhyXNXt5aCMc5A02HI8zq5qU4MN9r3xxyL',
      name: '封逸飞',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '历史爱好者',
      title: '诸葛亮去世后，刘禅为什么还能当30年...',
      content: '首先，诸葛亮于234年10月8日病逝，而刘禅的在位时间为223年-263年，诸葛亮去世后，刘禅维持了蜀...',
      comment: '0',
      like: '0',
      date: '昨天',
    },
    {
      id: 6,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRIrgAFVrwuAFhmXEgarItWPgeOondcAZVA8W9R9O1MsubJGX1Cg',
      name: '黄卓涛',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '吃瓜群众',
      title: '王莽',
      content: '多年以后，面对涌入长安的更始军士兵，新帝王莽将会想起众人劝进那一幕。',
      comment: '0',
      like: '0',
      date: '昨天',
    },
    {
      id: 7,
      avatar: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmRiT7fowGab96lj4phSqzKZvH56CgNfcirFte4qQI6AUe5Hz3',
      name: '杨承龙',
      iconName: 'ios-paw',
      iconSignature: 'ios-bonfire',
      signature: '吃瓜群众',
      title: '幸运皇帝',
      content: '中国历史上的皇帝可谓数不胜数，但是想当皇帝也要有狗屎运才行，且看以下中国历史上六大幸运皇帝排行：...',
      comment: '0',
      like: '0',
      date: '昨天',
    }],
  },
};
