import Colors from '../res/colors';

export default {
  namespace: 'settings',

  state: {
    medals: [{
      id: 1,
      backgroundColorLarge: Colors.backgroundColorOrange,
      backgroundColorMedium: Colors.backgroundColorGold,
      backgroundColorSmall: Colors.backgroundColorOrange,
      icon: 'ios-shirt',
      iconColor: Colors.iconColorDarkRed,
      achievement: '初出茅庐',
    },
    {
      id: 2,
      backgroundColorLarge: Colors.backgroundColorSteelBlue,
      backgroundColorMedium: Colors.backgroundColorSkyBlue,
      backgroundColorSmall: Colors.backgroundColorSteelBlue,
      icon: 'ios-body',
      iconColor: Colors.iconColorDarkRed,
      achievement: '持之以恒',
    },
    {
      id: 3,
      backgroundColorLarge: Colors.backgroundColorDarkSalmon,
      backgroundColorMedium: Colors.backgroundColorPeachPuff,
      backgroundColorSmall: Colors.backgroundColorDarkSalmon,
      icon: 'ios-body',
      iconColor: Colors.iconColorDarkRed,
      achievement: '持之以恒',
    },
    {
      id: 4,
      backgroundColorLarge: Colors.backgroundColorIndianRed,
      backgroundColorMedium: Colors.backgroundColordPink,
      backgroundColorSmall: Colors.backgroundColorIndianRed,
      icon: 'ios-body',
      iconColor: Colors.iconColorDarkRed,
      achievement: '持之以恒',
    },
    {
      id: 5,
      backgroundColorLarge: Colors.backgroundColorGray,
      backgroundColorMedium: Colors.backgroundColorGray,
      backgroundColorSmall: Colors.backgroundColorGray,
      icon: 'ios-leaf',
      iconColor: Colors.iconColorBlack,
      achievement: '授人以渔',
    },
    {
      id: 6,
      backgroundColorLarge: Colors.backgroundColorGray,
      backgroundColorMedium: Colors.backgroundColorGray,
      backgroundColorSmall: Colors.backgroundColorGray,
      icon: 'ios-leaf',
      iconColor: Colors.iconColorBlack,
      achievement: '授人以渔',
    },
    {
      id: 7,
      backgroundColorLarge: Colors.backgroundColorGray,
      backgroundColorMedium: Colors.backgroundColorGray,
      backgroundColorSmall: Colors.backgroundColorGray,
      icon: 'ios-leaf',
      iconColor: Colors.iconColorBlack,
      achievement: '授人以渔',
    },
    {
      id: 8,
      backgroundColorLarge: Colors.backgroundColorGray,
      backgroundColorMedium: Colors.backgroundColorGray,
      backgroundColorSmall: Colors.backgroundColorGray,
      icon: 'ios-brush',
      iconColor: Colors.iconColorBlack,
      achievement: '下笔成章',
    },
    {
      id: 9,
      backgroundColorLarge: Colors.backgroundColorGray,
      backgroundColorMedium: Colors.backgroundColorGray,
      backgroundColorSmall: Colors.backgroundColorGray,
      icon: 'ios-brush',
      iconColor: Colors.iconColorBlack,
      achievement: '下笔成章',
    },
    {
      id: 10,
      backgroundColorLarge: Colors.backgroundColorGray,
      backgroundColorMedium: Colors.backgroundColorGray,
      backgroundColorSmall: Colors.backgroundColorGray,
      icon: 'ios-brush',
      iconColor: Colors.iconColorBlack,
      achievement: '下笔成章',
    },
    {
      id: 11,
      backgroundColorLarge: Colors.backgroundColorGray,
      backgroundColorMedium: Colors.backgroundColorGray,
      backgroundColorSmall: Colors.backgroundColorGray,
      icon: 'ios-walk',
      iconColor: Colors.iconColorBlack,
      achievement: '勤学苦练',
    },
    {
      id: 12,
      backgroundColorLarge: Colors.backgroundColorGray,
      backgroundColorMedium: Colors.backgroundColorGray,
      backgroundColorSmall: Colors.backgroundColorGray,
      icon: 'ios-walk',
      iconColor: Colors.iconColorBlack,
      achievement: '勤学苦练',
    },
    {
      id: 13,
      backgroundColorLarge: Colors.backgroundColorGray,
      backgroundColorMedium: Colors.backgroundColorGray,
      backgroundColorSmall: Colors.backgroundColorGray,
      icon: 'ios-walk',
      iconColor: Colors.iconColorBlack,
      achievement: '勤学苦练',
    }],
  },
};
